config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :agents, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/agent.rb
class Agent < ApplicationRecord
  with_options presence: true do
    validates :user_id
    validates :company_name
    validates :company_location

    with_options format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/ } do
      validates :first_name
      validates :last_name
    end
    with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
      validates :last_name_kana
      validates :first_name_kana
    end
  end

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f / 5 * 100
    end
  end

  def self.search(search)
    if search != ''
      Agent.where(
        'last_name LIKE(?) OR first_name LIKE(?) OR last_name_kana LIKE(?) OR first_name_kana LIKE(?) OR company_name LIKE(?) OR company_location LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
      )
    else
      Agent.all
    end
  end

  has_many :reviews, dependent: :destroy
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/close_deal.rb
class CloseDeal < ActiveHash::Base
  self.data = [
    { id: 1, name: '取引済み' },
    { id: 2, name: '取引していない' },
    { id: 3, name: '取引予定' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :reviews
end

app/models/deal_type.rb
class DealType < ActiveHash::Base
  self.data = [
    { id: 1, name: '賃貸' },
    { id: 2, name: '売買' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :deal_type
  belongs_to :close_deal

  with_options presence: true do                       # 以下のものが存在している時のみに保存されるようにバリデーションをかけた
    validates :user_id
    validates :agent_id
    validates :content
    validates :score # ちゃんとしたバリデーション書く
    validates :deal_type_id
    validates :close_deal_id
  end

  validates :deal_type_id, format: { with: /\A[1-3]\z/ }     # deal_type_idには1,2,3のときのみ保存する
  validates :close_deal_id, format: { with: /\A[1-4]\z/ }    # close_deal_idには1,2,3,4のときのみ保存する

  belongs_to :user
  belongs_to :agent
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :reviews, dependent: :destroy
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new]

  def index
    @agents = Agent.all
  end

  def show
    @agent = Agent.find(params[:id])
    @review = Review.new
  end

  def new
    @agent = Agent.new
  end

  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      redirect_to agents_path
    else
      render :new
    end
  end

  def search
    @agents = Agent.search(params[:keyword])
  end

  private

  def agent_params
    params.require(:agent).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :company_name,
                                  :company_location).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    redirect_to agents_path if user_signed_in?
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @agent = Agent.find(params[:agent_id])
    @reviews = @agent.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to agent_reviews_path(@review.agent_id)
    else
      @agent = Agent.find(params[:agent_id])
      render 'agents/show'
    end
  end

  def edit
    @agent = Agent.find(params[:agent_id])
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])       # DRY
    if @review.update(review_params)
      redirect_to agent_reviews_path(@review.agent_id)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])       # DRY
    @review.destroy if @review.user_id == current_user.id
    redirect_to agent_reviews_path(params[:agent_id])
  end

  private

  def review_params
    params.require(:review).permit(:agent_id, :score, :deal_type_id, :close_deal_id, :content)
  end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/agents/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with(url: search_agents_path, local: true, method: :get, class: "field has-addons") do |form| %>
          <%= form.text_field :keyword, placeholder: "営業マンを検索する", class: "input" %>
          <%= form.submit "検索", class: "button is-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @agents.each do |agent| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= agent.last_name %> <%= agent.first_name %>
                <span class="has-text-weight-light is-italic is-size-7">(<%= agent.last_name_kana %> <%= agent.first_name_kana %>)</span>
              </p>
            </header>
            <div class="card-content">
              所属会社： <%= agent.company_name %><br>
              場所： <%= agent.company_location %><br>
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width:  <%= agent.review_score_percentage %>%">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                  <%= agent.avg_score %>点（<%= agent.reviews.count %>件のレビュー）
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
            <%= link_to agent_reviews_path(agent), class: "button card-footer-item" do %>
            レビューを見る
            <% end %>
            <%= link_to agent_path(agent), class: "button card-footer-item" do %>
            レビューを書く
            <% end %>
            </footer>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/agents/new.html.erb
<% if @agent.errors.any? %>
  <div class="notification is-danger">
    <h2><%= @agent.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="title is-2 is-centered has-text-white mt-6 mb-0">新規営業マン登録</div>
<section class="section pt-0">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="mt-3">
          <%= form_with model: @agent, url: agents_path, local: true do |f| %>

          <div class="field">
            <label class="label has-text-white">お名前</label>
            <div class="columns">
              <div class="control column">
                <%= f.text_field :last_name, class: "input ", placeholder: "姓" %>
              </div>
              <div class="control column">
                <%= f.text_field :first_name, class: "input ", placeholder: "名" %>
              </div>
            </div>
          </div>

          <div class="field">
            <label class="label has-text-white">お名前カナ(全角)</label>
            <div class="columns">
              <div class="control column">
                <%= f.text_field :last_name_kana, class: "input ", placeholder: "姓カナ" %>
              </div>
              <div class="control column">
                <%= f.text_field :first_name_kana, class: "input ", placeholder: "名カナ" %>
              </div>
            </div>
          </div>

          <div class="field">
            <label class="label has-text-white">所属している会社情報</label>
            <div class="control">
              <%= f.text_field :company_name, class: "input ", placeholder: "会社名" %>
            </div>
            <div class="control mt-2">
              <%= f.text_field :company_location, class: "input ", placeholder: "住所(例: 東京都千代田区永田町1-7-1)" %>
            </div>
          </div>

          <%= f.submit "登録する", class: "button is-primary  mt-3" %>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/agents/search.html.erb
<div class="section pb-0">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with(url: search_agents_path, local: true, method: :get, class: "field has-addons") do |form| %>
          <%= form.text_field :keyword, placeholder: "営業マンを検索する", class: "input" %>
          <%= form.submit "検索", class: "button is-info" %>
        <% end %>
        <div>
          次の検索結果を表示しています:<span class="has-text-weight-bold is-size-4"> <%= params[:keyword] %></span>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @agents.each do |agent| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= agent.last_name %> <%= agent.first_name %>
                <span class="has-text-weight-light is-italic is-size-7">(<%= agent.last_name_kana %> <%= agent.first_name_kana %>)</span>
              </p>
            </header>
            <div class="card-content">
              所属会社： <%= agent.company_name %><br>
              場所： <%= agent.company_location %><br>
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width:  <%= agent.review_score_percentage %>%">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                  <%= agent.avg_score %>点（<%= agent.reviews.count %>件のレビュー）
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
            <%= link_to agent_reviews_path(agent), class: "button card-footer-item" do %>
            レビューを見る
            <% end %>
            <%= link_to agent_path(agent), class: "button card-footer-item" do %>
            レビューを書く
            <% end %>
            </footer>
          </div>
        <% end %>
        <div class="is-centered">
          <%= link_to new_agent_path, class: "button is-primary  mt-3" do %>
            新しい営業マンを追加する
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/agents/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @agent.last_name %> <%= @agent.first_name %>
              <span class="has-text-weight-light is-italic is-size-7">(<%= @agent.last_name_kana %> <%= @agent.first_name_kana %>)</span>
            </p>
          </header>
          <div class="card-content">
            所属会社： <%= @agent.company_name %><br>
            場所： <%= @agent.company_location %><br>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @agent.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @agent.avg_score %>点（<%= @agent.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <p class="is-size-4 mb-3">レビューを書く</p>
        <%= render 'reviews/form', review: @review, agent: @agent %>
      </div>
    </div>
  </div>
</section>

app/views/homes/top.html.erb
<section class="section mt-6">   <%# margin top 6 はnavbarのために残しておく%>
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
          <p class="is-size-1 has-text-weight-bold has-text-centered is-size-3-touch">レビューをして信頼できる営業マンに会おう</p>
          <br>
          <div class="columns is-centered">
            <div class="column is-3">
              <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
              <br>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-fullwidth" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgentReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/539d7edbbb.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-3" style="font-family: cursive; color: grey;">Smoothly(仮)</strong>
          <% end %>
        </p>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to agents_path, class: "navbar-item" do %>
            営業マン一覧
          <% end %>
          <%= link_to new_agent_path, class: "navbar-item" do %>
            新規営業マン登録
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ <%= current_user.nickname %> さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <body>

    <%# フラッシュメッセージを追加%>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reviews/_form-edit.html.erb
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="rating-box mt-3">
  <%= form_with model: @review, url: agent_review_path(@review.agent_id, @review.id), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :agent_id, value: agent.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <div class="select mb-1">
      <%= f.collection_select(:deal_type_id, DealType.all, :id, :name, {include_blank: true, class:"genre-select"}) %>
    </div>
    <div class="select mb-1">
      <%= f.collection_select(:close_deal_id, CloseDeal.all, :id, :name, {include_blank: true, class:"genre-select"}) %>
    </div>
    <%= f.text_area :content, class: "textarea is-medium"%>
    <%= f.submit "保存", class: "button is-primary  mt-3" %>
    <%= link_to "他のレビューを見る", agent_reviews_path(agent), class: "button mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="rating-box mt-3">
  <%= form_with model: @review, url: agent_reviews_path(agent), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :agent_id, value: agent.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <div class="select mb-1">
      <%= f.collection_select(:deal_type_id, DealType.all, :id, :name, {include_blank: true, class:"genre-select"}) %>
    </div>
    <div class="select mb-1">
      <%= f.collection_select(:close_deal_id, CloseDeal.all, :id, :name, {include_blank: true, class:"genre-select"}) %>
    </div>
    <%= f.text_area :content, class: "textarea is-medium"%>
    <%= f.submit "保存", class: "button is-primary  mt-3" %>
    <%= link_to "他のレビューを見る", agent_reviews_path(agent), class: "button mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/edit.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @agent.last_name %> <%= @agent.first_name %>
              <span class="has-text-weight-light is-italic is-size-7">(<%= @agent.last_name_kana %> <%= @agent.first_name_kana %>)</span>
            </p>
          </header>
          <div class="card-content">
            所属会社： <%= @agent.company_name %><br>
            場所： <%= @agent.company_location %><br>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @agent.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @agent.avg_score %>点（<%= @agent.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <p class="is-size-4 mb-3">レビューを編集する</p>
        <%= render 'reviews/form-edit', review: @review, agent: @agent %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-two-thirds">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @agent.last_name %> <%= @agent.first_name %>
              <span class="has-text-weight-light is-italic is-size-7">(<%= @agent.last_name_kana %> <%= @agent.first_name_kana %>)</span>
            </p>
          </header>
          <div class="card-content">
            所属会社： <%= @agent.company_name %><br>
            場所： <%= @agent.company_location %><br>
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @agent.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @agent.avg_score %>点（<%= @agent.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>

        <h4 class="title is-2 is-centered has-text-white">クチコミ</h4>


        <% @reviews.each do |review| %>
        <div class="card review_card mb-4">
          <header class="card-header">
            <div class="card-header-title">
              <%= review.user.nickname %>
            </div>
          </header>
          <div class="card-content pt-2">
            <div class="content">
              <div class="star-rating mb-4">
                <div class="star-rating-front" style="width: <%= review.score * 20 %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <%= simple_format(review.content) %>
              <div class="has-text-right is-italic" ><%= l review.updated_at %></div>
            </div>
          </div>
          <% if user_signed_in? %>
            <%if current_user.id == review.user_id %>
              <footer class="card-footer">
                <%= link_to '編集する', edit_agent_review_path(review.agent_id, review.id), method: :get, class: "card-footer-item" %>
                <%= link_to '削除する', agent_review_path(review.agent_id, review.id), method: :delete, class: "card-footer-item" %>
              </footer>
            <% end %>
          <% end %>

        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>